services:
  postgres:
    image: postgres:15-alpine
    container_name: ev-booking-staging-postgres
    environment:
      POSTGRES_DB: ev_booking_staging_db
      POSTGRES_USER: ev_staging_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-StaG1ng_P@ssw0rd_2024!}
    ports:
      - "5433:5432"
    volumes:
      - postgres_staging_data:/var/lib/postgresql/data
    networks:
      - ev-booking-staging-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ev_staging_user -d ev_booking_staging_db && psql -U ev_staging_user -d ev_booking_staging_db -c 'SELECT 1;'"]
      interval: 15s
      timeout: 10s
      retries: 8
      start_period: 90s  # Add this - crucial for Spring Boot

  redis:
    image: redis:7-alpine
    container_name: ev-booking-staging-redis
    ports:
      - "6380:6379"
    volumes:
      - redis_staging_data:/data
    networks:
      - ev-booking-staging-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

  app:
    build:
      context: .
      dockerfile: Dockerfile.staging
    container_name: ev-booking-staging-app
    environment:
      SPRING_PROFILES_ACTIVE: staging
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ev_booking_staging_db
      DB_USERNAME: ev_staging_user
      DB_PASSWORD: ${DB_PASSWORD:-StaG1ng_P@ssw0rd_2024!}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET_KEY: ${JWT_SECRET_KEY:-staging-super-secret-key}
      MAIL_USERNAME: ${MAIL_USERNAME:-staging@evbooking.com}
      MAIL_PASSWORD: ${MAIL_PASSWORD:-staging_mail_password}
      STRIPE_PUBLIC_KEY: ${STRIPE_PUBLIC_KEY_STAGING:-pk_test_staging}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY_STAGING:-sk_test_staging}
    ports:
      - "8081:8080"
    depends_on:
      - postgres
      - redis
    networks:
      - ev-booking-staging-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 90s
    volumes:
      - staging_uploads:/app/uploads
      - staging_logs:/app/logs

volumes:
  postgres_staging_data:
  redis_staging_data:
  staging_uploads:
  staging_logs:

networks:
  ev-booking-staging-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16