spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:prod-postgres}:${DB_PORT:5432}/${DB_NAME:ev_booking_prod_db}
    username: ${DB_USERNAME:ev_prod_user}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 60000

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          batch_size: 25
          order_inserts: true
          order_updates: true
          fetch_size: 50
        connection:
          provider_disables_autocommit: true

  liquibase:
    contexts: production

  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration: ${JWT_EXPIRATION:1800000}

  cache:
    type: redis
    redis:
      host: ${REDIS_HOST:prod-redis}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}
      timeout: 2000ms
      ssl: true
      lettuce:
        pool:
          max-active: 16
          max-idle: 8
          min-idle: 4

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:noreply@evbooking.com}
    password: ${MAIL_PASSWORD}

logging:
  level:
    com.evbooking: INFO
    org.springframework.security: ERROR
    org.hibernate.SQL: ERROR
  file:
    name: logs/ev-booking-production.log
  logback:
    rollingpolicy:
      max-file-size: 500MB
      max-history: 90
      total-size-cap: 10GB

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: never
  metrics:
    export:
      prometheus:
        enabled: true
  security:
    enabled: true

server:
  ssl:
    enabled: ${SSL_ENABLED:true}
    key-store: ${SSL_KEYSTORE_PATH:/app/ssl/keystore.p12}
    key-store-password: ${SSL_KEYSTORE_PASSWORD}
    key-store-type: PKCS12

app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:https://evbooking.com,https://admin.evbooking.com,https://mobile.evbooking.com}
  file-upload:
    max-size: ${MAX_FILE_SIZE:10MB}
    upload-path: ${UPLOAD_PATH:/app/uploads}
  payment:
    stripe:
      public-key: ${STRIPE_PUBLIC_KEY}
      secret-key: ${STRIPE_SECRET_KEY}
  notification:
    enabled: true
    webhook-url: ${WEBHOOK_URL:https://webhook.evbooking.com}
  rate-limiting:
    enabled: true
    requests-per-minute: ${RATE_LIMIT_RPM:100}