name: Deploy to Staging

on:
  push:
    branches: [ development ]
  workflow_dispatch:

env:
  DOCKER_IMAGE: ${{ secrets.DOCKER_USERNAME }}/ev-booking-backend

jobs:
  deploy-staging:
    name: Deploy to Staging Environment
    runs-on: ubuntu-latest
    environment: staging

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile.staging
        push: true
        tags: ${{ env.DOCKER_IMAGE }}:staging-${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.STAGING_SSH_PRIVATE_KEY }}

    - name: Add staging server to known hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.STAGING_HOST }} >> ~/.ssh/known_hosts

    - name: Create deployment directory on staging server
      run: |
        ssh ${{ secrets.STAGING_USER }}@${{ secrets.STAGING_HOST }} '
          mkdir -p ~/ev-booking-staging
        '

    - name: Copy deployment files to staging server
      run: |
        scp -r docker-compose.staging.yml \
               Dockerfile.staging \
               nginx/staging.conf \
               scripts/deployment/deploy-staging.sh \
               .env.staging.example \
               ${{ secrets.STAGING_USER }}@${{ secrets.STAGING_HOST }}:~/ev-booking-staging/

    - name: Create environment file on staging server
      run: |
        ssh ${{ secrets.STAGING_USER }}@${{ secrets.STAGING_HOST }} '
          cd ~/ev-booking-staging
          cat > .env.staging << EOF
          POSTGRES_PASSWORD=${{ secrets.STAGING_POSTGRES_PASSWORD }}
          DB_PASSWORD=${{ secrets.STAGING_DB_PASSWORD }}
          REDIS_PASSWORD=${{ secrets.STAGING_REDIS_PASSWORD }}
          JWT_SECRET_KEY=${{ secrets.STAGING_JWT_SECRET_KEY }}
          MAIL_USERNAME=${{ secrets.STAGING_MAIL_USERNAME }}
          MAIL_PASSWORD=${{ secrets.STAGING_MAIL_PASSWORD }}
          STRIPE_PUBLIC_KEY_STAGING=${{ secrets.STAGING_STRIPE_PUBLIC_KEY }}
          STRIPE_SECRET_KEY_STAGING=${{ secrets.STAGING_STRIPE_SECRET_KEY }}
          CORS_ALLOWED_ORIGINS=${{ secrets.STAGING_CORS_ALLOWED_ORIGINS }}
          WEBHOOK_URL=${{ secrets.STAGING_WEBHOOK_URL }}
          DOCKER_IMAGE_TAG=staging-${{ github.sha }}
          EOF
        '

    - name: Update Docker image tag in compose file
      run: |
        ssh ${{ secrets.STAGING_USER }}@${{ secrets.STAGING_HOST }} '
          cd ~/ev-booking-staging
          sed -i "s|build:|image: ${{ env.DOCKER_IMAGE }}:staging-${{ github.sha }}|g" docker-compose.staging.yml
          sed -i "/dockerfile:/d" docker-compose.staging.yml
          sed -i "/context:/d" docker-compose.staging.yml
        '

    - name: Deploy to staging
      run: |
        ssh ${{ secrets.STAGING_USER }}@${{ secrets.STAGING_HOST }} '
          cd ~/ev-booking-staging
          chmod +x deploy-staging.sh
          ./deploy-staging.sh
        '

    - name: Run health checks
      run: |
        ssh ${{ secrets.STAGING_USER }}@${{ secrets.STAGING_HOST }} '
          echo "Waiting for application to start..."
          sleep 30

          # Health check with retry
          for i in {1..10}; do
            if curl -f http://localhost:8081/api/actuator/health; then
              echo "Health check passed!"
              break
            else
              echo "Health check failed, attempt $i/10"
              sleep 10
            fi
          done

          # Final health check
          curl -f http://localhost:8081/api/actuator/health || exit 1
        '

    - name: Run smoke tests
      run: |
        ssh ${{ secrets.STAGING_USER }}@${{ secrets.STAGING_HOST }} '
          # Test API endpoints
          echo "Running smoke tests..."

          # Test health endpoint
          curl -f http://localhost:8081/api/actuator/health

          # Test info endpoint
          curl -f http://localhost:8081/api/actuator/info

          # Test swagger endpoint
          curl -f http://localhost:8081/api/swagger-ui.html

          echo "Smoke tests passed!"
        '

    - name: Cleanup old images
      run: |
        ssh ${{ secrets.STAGING_USER }}@${{ secrets.STAGING_HOST }} '
          # Remove old Docker images to save space
          docker image prune -a -f --filter "until=72h"
        '

    - name: Send Slack notification
      if: always()
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        channel: '#deployments'
        webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
        fields: |
          {
            "attachments": [
              {
                "color": "${{ job.status == 'success' && 'good' || 'danger' }}",
                "fields": [
                  {
                    "title": "Environment",
                    "value": "Staging",
                    "short": true
                  },
                  {
                    "title": "Status",
                    "value": "${{ job.status }}",
                    "short": true
                  },
                  {
                    "title": "Branch",
                    "value": "${{ github.ref_name }}",
                    "short": true
                  },
                  {
                    "title": "Commit",
                    "value": "${{ github.sha }}",
                    "short": true
                  },
                  {
                    "title": "URL",
                    "value": "https://staging.evbooking.com",
                    "short": false
                  }
                ]
              }
            ]
          }

  post-deployment-tests:
    name: Post-deployment Tests
    runs-on: ubuntu-latest
    needs: deploy-staging
    if: success()

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js for API tests
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Newman (Postman CLI)
      run: npm install -g newman

    - name: Run API tests
      run: |
        # Run Postman collection against staging
        newman run tests/postman/ev-booking-api.postman_collection.json \
          -e tests/postman/staging.postman_environment.json \
          --reporters cli,json \
          --reporter-json-export staging-test-results.json

    - name: Upload test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: staging-api-test-results
        path: staging-test-results.json